SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Populating game_providers
-- ----------------------------

-- 可选: 如果你想清空现有数据，请取消注释下一行
TRUNCATE TABLE `game_providers`;

INSERT INTO `game_providers` (`id`, `code`, `name`, `status`, `api_config`) VALUES
(1, 'Pragmatic Play Slots', 'Pragmatic Play Slots', 1, NULL),
(2, 'YeeBet Casino', 'YeeBet Casino', 1, NULL),
(3, 'NextSpin', 'NextSpin', 1, NULL),
(4, 'Obet33', 'Obet33', 1, NULL),
(5, '93Connect', '93Connect', 1, NULL),
(6, 'M8 Sports', 'M8 Sports', 1, NULL),
(7, 'SV388', 'SV388', 1, NULL),
(8, 'SpadeGaming', 'SpadeGaming', 1, NULL),
(9, 'YGG', 'YGG', 1, NULL),
(10, 'MicroGaming Plus Slots', 'MicroGaming Plus Slots', 1, NULL),
(11, 'AE Sexy', 'AE Sexy', 1, NULL),
(12, 'Evolution Gaming', 'Evolution Gaming', 1, NULL),
(13, 'Live22', 'Live22', 1, NULL),
(14, 'WMT', 'WMT', 1, NULL),
(15, 'LFC', 'LFC', 1, NULL),
(16, 'JILI', 'JILI', 1, NULL),
(17, 'KingMidas', 'KingMidas', 1, NULL),
(18, 'JDB', 'JDB', 1, NULL),
(19, 'Joker', 'Joker', 1, NULL),
(20, 'S128', 'S128', 1, NULL),
(21, 'Pragmatic Play Casino', 'Pragmatic Play Casino', 1, NULL),
(22, 'PT', 'PT', 1, NULL),
(23, 'PGSoft', 'PGSoft', 1, NULL),
(24, 'Fachai', 'Fachai', 1, NULL),
(25, 'AVT', 'AVT', 1, NULL),
(26, 'Pegasus', 'Pegasus', 1, NULL),
(27, 'AllBet', 'AllBet', 1, NULL),
(28, 'AdvantPlay', 'AdvantPlay', 1, NULL),
(29, 'Habanero', 'Habanero', 1, NULL),
(30, 'Endorphina', 'Endorphina', 1, NULL),
(31, 'CQ9 Slots', 'CQ9 Slots', 1, NULL),
(32, 'DragoonSoft', 'DragoonSoft', 1, NULL),
(33, 'WonCasino', 'WonCasino', 1, NULL),
(34, 'PTB', 'PTB', 1, NULL),
(35, 'Ace333', 'Ace333', 1, NULL),
(36, 'Naga Games', 'Naga Games', 1, NULL),
(37, 'Rich88', 'Rich88', 1, NULL),
(38, 'KA Gaming', 'KA Gaming', 1, NULL),
(39, 'ClotPlay', 'ClotPlay', 1, NULL),
(40, 'SBO Sports', 'SBO Sports', 1, NULL),
(41, 'RCB988', 'RCB988', 1, NULL),
(42, 'NetEnt', 'NetEnt', 1, NULL),
(43, 'RedTiger', 'RedTiger', 1, NULL),
(44, 'BigTimeGaming', 'BigTimeGaming', 1, NULL),
(45, 'NoLimitCity', 'NoLimitCity', 1, NULL),
(46, 'Funta Gaming', 'Funta Gaming', 1, NULL),
(47, 'UU Slots', 'UU Slots', 1, NULL),
(48, 'RLG', 'RLG', 1, NULL),
(49, 'VW2 OB', 'VW2 OB', 1, NULL),
(50, 'X2', 'X2', 1, NULL),
(51, 'VPlus', 'VPlus', 1, NULL),
(52, 'TGK', 'TGK', 1, NULL),
(53, 'World Entertainment', 'World Entertainment', 1, NULL),
(54, 'Creative Gaming', 'Creative Gaming', 1, NULL),
(55, 'PIN', 'PIN', 1, NULL),
(56, 'Amigo Gaming', 'Amigo Gaming', 1, NULL),
(57, 'TRS', 'TRS', 1, NULL),
(58, 'Tiger 9', 'Tiger 9', 1, NULL),
(59, 'Good Fortune Gaming', 'Good Fortune Gaming', 1, NULL),
(60, 'ILU', 'ILU', 1, NULL),
(61, 'MegaH5', 'MegaH5', 1, NULL),
(62, 'PYK', 'PYK', 1, NULL),
(63, 'EpicWin', 'EpicWin', 1, NULL),
(64, 'ASR', 'ASR', 1, NULL),
(65, 'Genesis', 'Genesis', 1, NULL),
(66, 'WS Sports', 'WS Sports', 1, NULL),
(67, 'UG', 'UG', 1, NULL),
(68, 'BPG', 'BPG', 1, NULL),
(69, 'Novomatic', 'Novomatic', 1, NULL),
(70, 'Octoplay', 'Octoplay', 1, NULL),
(71, 'TRSB', 'TRSB', 1, NULL),
(72, 'SMS', 'SMS', 1, NULL),
(73, 'VW2 PlayAce Casino', 'VW2 PlayAce Casino', 1, NULL),
(74, 'VW2 PlayAce Slot', 'VW2 PlayAce Slot', 1, NULL),
(75, 'SBO2', 'SBO2', 1, NULL),
(76, 'Spribe', 'Spribe', 1, NULL),
(77, 'Rich Game Slots', 'Rich Game Slots', 1, NULL),
(78, 'RGS2', 'RGS2', 1, NULL),
(79, 'PlayAce Casino', 'PlayAce Casino', 1, NULL),
(80, 'PlayAce Slot XIN', 'PlayAce Slot XIN', 1, NULL),
(81, 'MicroGaming Plus Casino', 'MicroGaming Plus Casino', 1, NULL),
(82, 'CQ9 Casino', 'CQ9 Casino', 1, NULL),
(83, 'WF Gaming', 'WF Gaming', 1, NULL),
(84, 'RichGaming', 'RichGaming', 1, NULL),
(85, 'AFB3', 'AFB3', 1, NULL),
(86, 'Wazdan', 'Wazdan', 1, NULL),
(87, 'BGaming', 'BGaming', 1, NULL),
(88, 'Playtech Slots', 'Playtech Slots', 1, NULL),
(89, 'Playtech Casino', 'Playtech Casino', 1, NULL),
(90, 'BTI', 'BTI', 1, NULL),
(91, 'VoltEnt', 'VoltEnt', 1, NULL),
(92, 'TVBet', 'TVBet', 1, NULL),
(93, 'APL', 'APL', 1, NULL),
(94, 'DGM', 'DGM', 1, NULL),
(95, 'PlayAce Slots AGIN', 'PlayAce Slots AGIN', 1, NULL);

SET FOREIGN_KEY_CHECKS = 1;